-- MySQL Script generated by MySQL Workbench
-- Fri May 16 15:27:50 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `id_categoria` INT NOT NULL,
  `nomel` VARCHAR(100) NULL,
  `descrição` VARCHAR(200) NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fornecedor` (
  `id_fornecedor` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  `endereco` VARCHAR(100) NULL,
  `telefone` VARCHAR(25) NULL,
  `email` VARCHAR(150) NULL,
  `cnpj` VARCHAR(18) NULL,
  PRIMARY KEY (`id_fornecedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `id_produto` INT NOT NULL,
  `nome` VARCHAR(150) NULL,
  `preco` DECIMAL(10,2) NULL,
  `tamanho` VARCHAR(100) NULL,
  `cor` VARCHAR(50) NULL,
  `marca` VARCHAR(100) NULL,
  `categoria_id_categoria` INT NOT NULL,
  `fornecedor_id_fornecedor` INT NOT NULL,
  PRIMARY KEY (`id_produto`),
  INDEX `fk_Produto_categoria1_idx` (`categoria_id_categoria` ASC) VISIBLE,
  INDEX `fk_Produto_fornecedor1_idx` (`fornecedor_id_fornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_categoria1`
    FOREIGN KEY (`categoria_id_categoria`)
    REFERENCES `mydb`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_fornecedor1`
    FOREIGN KEY (`fornecedor_id_fornecedor`)
    REFERENCES `mydb`.`fornecedor` (`id_fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `id_cliente` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  `endereco` VARCHAR(100) NULL,
  `telefone` VARCHAR(20) NULL,
  `email` VARCHAR(100) NULL,
  `cadastro_data` DATE NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionario` (
  `id_funcionario` INT NOT NULL,
  `cpf` VARCHAR(25) NULL,
  `nome` VARCHAR(100) NULL,
  `cargo` VARCHAR(45) NULL,
  `telefone` VARCHAR(25) NULL,
  `email` VARCHAR(100) NULL,
  PRIMARY KEY (`id_funcionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`desconto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`desconto` (
  `id_desconto` INT NOT NULL,
  `desconto` DECIMAL(10,2) NULL,
  `descricao` VARCHAR(200) NULL,
  PRIMARY KEY (`id_desconto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`venda` (
  `id_venda` INT NOT NULL,
  `data_venda` DATE NULL,
  `desconto` DECIMAL(10,2) NULL,
  `valor` DECIMAL(10,2) NULL,
  `id_cliente` INT NOT NULL,
  `funcionario_id_funcionario` INT NOT NULL,
  `desconto_id_desconto` INT NOT NULL,
  PRIMARY KEY (`id_venda`),
  INDEX `fk_venda_cliente1_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `fk_venda_funcionario1_idx` (`funcionario_id_funcionario` ASC) VISIBLE,
  INDEX `fk_venda_desconto1_idx` (`desconto_id_desconto` ASC) VISIBLE,
  CONSTRAINT `fk_venda_cliente1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `mydb`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_funcionario1`
    FOREIGN KEY (`funcionario_id_funcionario`)
    REFERENCES `mydb`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_desconto1`
    FOREIGN KEY (`desconto_id_desconto`)
    REFERENCES `mydb`.`desconto` (`id_desconto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estoque` (
  `id_estoque` INT NOT NULL,
  `cod_produto` INT NULL,
  `quantidade` INT NULL,
  `data_entrada` DATE NULL,
  `data_saida` DATE NULL,
  `id_produto` INT NOT NULL,
  PRIMARY KEY (`id_estoque`),
  INDEX `fk_estoque_Produto1_idx` (`id_produto` ASC) VISIBLE,
  CONSTRAINT `fk_estoque_Produto1`
    FOREIGN KEY (`id_produto`)
    REFERENCES `mydb`.`Produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venda_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`venda_produto` (
  `id_venda` INT NOT NULL,
  `id_produto` INT NULL,
  `quantidade` INT NULL,
  `valor` DECIMAL(10,2) NULL,
  `produto_id_produto` INT NOT NULL,
  `venda_id_venda` INT NOT NULL,
  PRIMARY KEY (`id_venda`),
  INDEX `fk_venda_produto_Produto_idx` (`produto_id_produto` ASC) VISIBLE,
  INDEX `fk_venda_produto_venda1_idx` (`venda_id_venda` ASC) VISIBLE,
  CONSTRAINT `fk_venda_produto_Produto`
    FOREIGN KEY (`produto_id_produto`)
    REFERENCES `mydb`.`Produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_produto_venda1`
    FOREIGN KEY (`venda_id_venda`)
    REFERENCES `mydb`.`venda` (`id_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`endereco_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`endereco_cliente` (
  `id_enderecocli` INT NOT NULL,
  `bairro` VARCHAR(50) NULL,
  `rua` VARCHAR(50) NULL,
  `cidade` VARCHAR(50) NULL,
  `uf` VARCHAR(2) NULL,
  `cep` VARCHAR(13) NULL,
  `cliente_id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_enderecocli`),
  INDEX `fk_endereco_cliente_cliente1_idx` (`cliente_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_cliente_cliente1`
    FOREIGN KEY (`cliente_id_cliente`)
    REFERENCES `mydb`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
